name: Run Courses 2 Automation Test

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Chọn chế độ test"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - specific
      test_file:
        description: "Tên file .feature cần test (Nếu chế độ test là specific | Không cần điền đuôi .feature)"
        required: false
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium behave

      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl

          # Install Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          # Get the Chrome major version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)

          # Get matching ChromeDriver version
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          curl -sS -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip -o chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run all tests
        if: ${{ github.event.inputs.mode == 'all' }}
        run: |
          python run_automation_test.py

      - name: Run specific test file with retry
        if: ${{ github.event.inputs.mode == 'specific' }}
        run: |
          if [ -z "${{ github.event.inputs.test_file }}" ]; then
            echo "Error: test_file input is required in 'specific' mode."
            exit 1
          fi
          behave features/templates/${{ github.event.inputs.test_file }}.feature
